spring:
  application:
    name: langdiary
  datasource:
    url: jdbc:postgresql://localhost:5432/langdiary_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database: PostgreSQL
    #show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/langdiary_db
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration/core,classpath:db/migration/dev
  security:
    user:
      name: user
      password: ${TMP_DEV_PW}